import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar_LY': {
      'Teacher': 'معلم',
      'Student': 'طالب',
      'parent':'ولي أمر',
      'Parent':'ولي أمر',
      'LogType': 'الدخول كـ مسجل حضور',
      'AppV': 'نسخة التطبيق v1.0',
      'WelcomeText': 'سجل دخولك كي تتمكن من استخدام التطبيق',
      'Username': 'اسم المستخدم',
      'Password': 'كلمة المرور',
      'LogIn': 'دخول',
      'Sign in': 'تسجيل دخول',
      'ErrorMsg': 'اسم المستخدم او كلمة المرور غير صحيحة',
       'Ok': 'موافق',
      'ChooseYourLanguage': 'اختار اللغة',
      'changelang': 'تغيير اللغة',
      'Calendar': 'التقويم',
      'Notification': 'الاشعارات',
      'Home': 'الرئيسية',
      'age': 'العمر',
      'class': 'الفصل',
      'city': 'المدينة',
      'fatherMo': 'رقم هاتف الاب',
      'motherMo': 'رقم هاتف الأم',
      'Profile': 'حسابي',
      'LogOut': 'خروج',
      'LogType': 'الدخول كـ مسجل حضور',
      'Perfect Environment for your children' : 'بيئة ممتازة لأطفالك',
      'Our School is Where you can watch your kids school performance from home': 'مدرستناتطبيق يمكنك من خلال تتبع أداء أطفالك',
      'All of your children in one place':'كل أطفالك في مكان واحد',
     'Now you can know when is your kids exam and also track their attendance':'الأن يمكنك معرفة أيام غياب طفلك وموعد الإختبارات',
     'Sign in As a teacher to manage your students':'سجل الدخول كمعلم لإدارة الطلبة',
      'Username or password is incorrect':'اسم المستخدم أو كلمة المرور خاطئة',
      'Create An Account':'إنشاء حساب',
      'Sign in As an Attendence Register to Manage Students': 'تسجيل الدخول كسمجل حضور',
      'Tests':'الإختبارات',
      'Attendence':'الحضور والغياب',
      'Tests & Exams Schedule':'جدول الإختبارات والإمتحانات',
      'Marks':'درجات',
      'No marks yet, try again later':'لايوجد درجات, الرجاء المحاولة لاحقا',
      'Search For Student':'البحث عن طالب',
      'Post Deleted':'تم حذف المنشور',
      'Add Post':'إضافة منشور',
      'Add Test':'إضافة إختبار',
      'Content':'المحتوى',
      'Post Added Succesfully':'تم إضافة المنشور بنجاح',
      'Save':'حفظ',
      'School Work':'أعمال السنة',
      'Please Enter Mark':'الرجاء إدخال الدررجة ',
      'Please Enter a valid mark':'الرجاء إدخال درجة صحيحة',
      'Final Exam':'درجة النهائي',
      'Please Review your data':'الرجاء مراجعة البيانات',
      'Create An Account':'إنشاء حساب',


    },

    'en_US': {
      'Sign in': 'Sign in',
      'Teacher': 'Teacher',
      'Student': 'Student',
      'Parent': 'Parent',
      'parent': 'parent',
      'LogType': 'Log in as a registered attendee',
      'AppV': 'App Version v1.0',
      'WelcomeText': 'Sign in to be able to use the application',
      'UserName': 'UserName',
      'PassWord': 'PassWord',
      'LogIn': 'LogIn',
      'ErrorMsg': 'The username or password is incorrect',
      'Ok': 'Ok',
      'ChooseYourLanguage': 'Choose Your Language',
      'changelang': 'change Language',
      'Calendar': 'Calendar',
      'Notification': 'Notification',
      'Home': 'Home',
      'age': 'Age',
      'class': 'Class',
      'city': 'city',
      'fatherMo': 'Father Mobile',
      'motherMo': 'Mother Mobile',
      'Profile': 'Profile',
      'LogOut': 'LogOut',
       'Perfect Environment for your children' : 'Perfect Environment for your children',
      'Our School is Where you can watch your kids school performance from home': 'Our School is Where you can watch your kids school performance from home',
      'All of your children in one place':'All of your children in one place',
     'Now you can know when is your kids exam and also track their attendance':'Now you can know when is your kids exam and also track their attendance',
     'Sign in As a teacher to manage your students':'Sign in As a teacher to manage your students',
      'Username or password is incorrect':'اسم المستخدم أو كلمة المرور خاطئة',
      'Create An Account':'Create An Account',
      'Sign in As an Attendence Register to Manage Students': 'Sign in As an Attendence Register to Manage Students',
      'Tests':'Tests',
      'Attendence':'Attendence',
      'Tests & Exams Schedule':'Tests & Exams Schedule',
      'Marks':'Marks',
      'No marks yet, try again later':'No marks yet, try again later',
      'Search For Student':'Search For Student',
      'Post Deleted':'Post Deleted',
      'Add Post':'Add Post',
      'Add Test':'Add Test',
      'Content':'Content',
      'Post Added Succesfully':'تم إضافة المنشور بنجاح',
      'Save':'حفظ',
      'School Work':'School Work',
      'Please Enter Mark':'Please Enter Mark',
      'Please Enter a valid mark':'Please Enter a valid mark',
      'Final Exam':'Final Exam',
      'Please Review your data':'Please Review your data',
      'Create An Account':'Create An Account',

    },
  };
}